#ifndef BPFLUT_CONST_H
#define BPFLUT_CONST_H

#define BPFLUT_WORKSPACE_DIR "_bpflut_workspace_"
#define BPFLUT_DIR BPFLUT_WORKSPACE_DIR "/.bpflut"
#define BPFLUT_IOS_DIR BPFLUT_DIR "/ios"
#define BPFLUT_IOS_RUNNER_DIR BPFLUT_WORKSPACE_DIR "/ios/Runner"
#define BPFLUT_IOS_EXPORTOPTIONS_PATH BPFLUT_IOS_RUNNER_DIR "/ExportOptions.plist"

#define BPFLUT_ANDROID_DIR BPFLUT_DIR "/android"
#define BPFLUT_IOS_CONFIG BPFLUT_IOS_DIR "/config.env"
#define BPFLUT_ANDROID_CONFIG BPFLUT_ANDROID_DIR "/config.env"

#endif
